version: "3.8"

services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - storage:/usr/storage/
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
  mongo_express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_URL: mongodb://db:27017

volumes:
  mongodb-data:
  storage:
